server:
port : 5000
spring:
jpa:
database: MYSQL
show-sql: true
database-platform: org.hibernate.dialect.MySQL8Dialect
hibernate:
ddl-auto: update
datasource:
url: jdbc://${rds.hostname}:${rds.port}/${rds.db.name}
username: ${rds.usename}
password: ${rds.password}